.\" Man page for Slackware-Commander
.\" Created by Anagnostakis Ioannis (aka rizitis)
.TH SLACKWARE-COMMANDER 1 "April 2024" "2.0.4" "Slackware-Commander"
.SH NAME
Slackware-Commander \- A gtkdialog and yad menu for Slackware system administration.
.SH SYNOPSIS
.B slackware-commander
.SH DESCRIPTION
Slackware-Commander opens a gtkdialog box. It provides an interface for common slackpkg commands, allowing you to manage Slackware system packages and files in a user-friendly manner. It includes options for editing slackpkg configuration files, viewing change logs, and accessing additional system tools.

The 'More Tools' button opens a secondary menu with additional tools, including SBKS (Slack Build Kernel Script), whoRyou (a terminal app for gathering system information), and slackpkg_build, which allows you to download and build packages from the official Slackware repository.

Slackware-Commander is designed to make Slackware system administration easier while keeping the KISS (Keep It Simple, Stupid) philosophy.

.SH SEE ALSO
https://github.com/rizitis/Slackware-Commander
.SH AUTHOR
Anagnostakis Ioannis (aka rizitis)
